name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container: mmmtastymmm/ubuntu-dev:ranges

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Build Directory
      run: mkdir build

    - name: CMake Generate
      working-directory: build
      run: cmake ..

    - name: CMake Build
      working-directory: build
      run: cmake --build .

    - name: Run Tests
      working-directory: build
      run: views_fun

